## <font color='blue'>NumPy Lab</font>
In this lab, you will use Numpy to implement simple mathematical functions, which are very frequently used in Deep Learning.

These functions are the building blocks of a Neural Network.

## <font color='blue'>1. ReLU Implementation</font>

**ReLU** stands for Rectified Linear Unit. It is defined as follows:

```
z = max(0, x)
```


<img src='https://www.learnopencv.com/wp-content/uploads/2020/01/c3_w1_ReLU.png'/>

In this part, you have to implement this ReLU function definition using NumPy.

So if the input is:
```
array([[ 1. ,  2. , -3. ],
       [ 2.5, -0.2,  6. ]])
```

You should return the following output:
```
array([[1. , 2. , 0. ],
       [2.5, 0. , 6. ]])
```

In [20]:
import numpy as np

In [25]:
def ReLU(array):
    return np.maximum(0, array)

# 0 if i<=0 else i for i in array

# array.clip(0)

#    for check_value in range(len(array)):
#        if check_value <= 0:
#            check_value == 0
#            return check_value
#        else:
#            return check_value

In [26]:
# test your result
a = np.array([[1, 2, -3], [2.5, -0.2, 6]])
ReLU(a)

array([[1. , 2. , 0. ],
       [2.5, 0. , 6. ]])

## <font color='blue'>2. Softmax Implementation</font>

Softmax is defined as follows:
$$
\text{softmax}(z_{i}) = \frac{\exp(z_i)}{\sum_j \exp(z_j)}
$$

For example, we have following an array as an input:
```
array([0.6, 5.2, 9.2])
```

Then, the function should return the following as output:
```
array([1.80761747e-04, 1.79829587e-02, 9.81836280e-01])
```

In [27]:
def softmax(array):
    e = np.exp(array)
    s = np.sum(np.exp(array))
    ret = e/s
    return ret

In [28]:
# Test your result
a = np.array([0.6, 5.2, 9.2])
softmax(a)

array([1.80761747e-04, 1.79829587e-02, 9.81836280e-01])

## <font color='blue'>3. Neural Network Neuron Implementation</font>


We all are familiar with the `1-dimensional` linear equation:

$$
y = mx + c
$$

We can re-write the equation as:

$$
y = w_1x + b
$$

We can write the `n-dimensional` linear equation as follows:

$$
y = w_1x_1 + w_2x_2 + ... + w_nx_n + b
$$


Following is a pictorial representation `n-dimensional` linear equations. This linear function is called a neuron in neural networks.

<img src='https://www.learnopencv.com/wp-content/uploads/2020/01/c3_w1_linear_equation.png'>

let's define $W$ as,
$$
W = \begin{bmatrix}
    w_1       & w_2 & w_3 & \dots & w_n
\end{bmatrix}
$$

and $X$ as,
$$
 X = \begin{bmatrix}
           x_{1} \\
           x_{2} \\
           \vdots \\
           x_{n}
         \end{bmatrix}
$$

Using above $W$ and $X$, we can re-write the n-dimensional linear equation as follows:

$$
y = WX + b
$$

In a neural network, $X$, $W$, $b$, and $y$ are called input, weight, bias, and output of the neuron, respectively.

In a neural network, usually, we use to have much more than one neuron. The same input $X$ passes through all neurons of the layer and gets output $y$ for each neuron. We don't have to calculate linear function for each neuron at a time; we can calculate all in one go using Numpy.

Let's assume we have `m` neurons. So we will have `m` output. Let's stack all weight horizontally and do matrix multiplication by input and add stacked $b$. It will give `m` output for all `m` neurons.


$$
W = \begin{bmatrix}
    w_{11}       & w_{12} & w_{13} & \dots & w_{1n} \\
    w_{21}       & w_{22} & w_{23} & \dots & w_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    w_{m1}       & w_{m2} & w_{m3} & \dots & w_{mn}
\end{bmatrix}
$$

$$
 B = \begin{bmatrix}
           b_{1} \\
           b_{2} \\
           \vdots \\
           b_{m}
         \end{bmatrix}
$$

$$
 Y = \begin{bmatrix}
           y_{1} \\
           y_{2} \\
           \vdots \\
           y_{m}
         \end{bmatrix}
$$

You have to implement the following function:
$$
Y = WX + B
$$
The function will take weight $W$, bias $B$, and input $X$ as arguments. You have to return outputs $Y$.

For example, arguments $W$, $B$ and $X$ are as follows:
```
W = np.array([[1.2, 0.3, 0.1], [.01, 2.1, 0.7]])
B = np.array([2.1, 0.89])
X = np.array([0.3, 6.8, 0.59])
```

Function should return:
```
array([ 4.559, 15.586])
```

In [30]:
def neural_network_neurons(W, B, X):
    y = np.matmul(W, X) + B
    return y

In [31]:
W = np.array([[1.2, 0.3, 0.1], [.01, 2.1, 0.7]])
B = np.array([2.1, 0.89])
X = np.array([0.3, 6.8, 0.59])

neural_network_neurons(W, B, X)

array([ 4.559, 15.586])