# <font color='blue'>Numpy intro</font>

### <font style="color:rgb(8,133,37)">Why do we need a special library for math and DL?</font>
Python provides data types such as lists / tuples out of the box. Then, why are we using special libraries for deep learning tasks, such as Pytorch or TensorFlow, and not using standard types?

The major reason is efficiency - In pure python, there are no primitive types for numbers, as in e.g. C language. All the data types in Python are objects with lots of properties and methods. You can see it using the `dir` function:

### <font style="color:rgb(8,133,37)">Python Issues</font>

- slow in tasks that require tons of simple math operations on numbers
- huge memory overhead due to storing plain numbers as objects
- runtime overhead during memory dereferencing - cache issues


NumPy is an abbreviation for "numerical python" and as it stands from the naming it provides a rich collection of operations on the numerical data types with a python interface. The core data structure of NumPy is `ndarray` - a multidimensional array. Let's take a look at its interface in comparison with plain python lists.

# <font style="color:blue">Basics of Numpy </font>
We will go over some of the useful operations of Numpy arrays, which are most commonly used in ML tasks.

## <font color='blue'>1. Basic Operations </font>
### <font style="color:rgb(8,133,37)">1.1. Python list to numpy array</font>


In [38]:
import numpy as np

In [39]:
py_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

np_array = np.array(py_list)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
py_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

np_array= np.array(py_list)
np_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### <font style="color:rgb(8,133,37)">1.2. Slicing and Indexing</font>


In [41]:
print('First row:\t\t\t{}'.format(np_array[0]))
print('First column:\t\t\t{}'.format(np_array[:, 0]))
print('3rd row 2nd column element:\t{}'.format(np_array[2][1]))
print('2nd onwards row and 2nd onwards column:\n{}'.format(np_array[1:, 1:]))
print('Last 2 rows and last 2 columns:\n{}'.format(np_array[-2:, -2:]))
print('Array with 3rd, 1st and 4th row:\n{}'.format(np_array[[2, 0, 3]]))

First row:			[1 2 3]
First column:			[ 1  4  7 10]
3rd row 2nd column element:	8
2nd onwards row and 2nd onwards column:
[[ 5  6]
 [ 8  9]
 [11 12]]
Last 2 rows and last 2 columns:
[[ 8  9]
 [11 12]]
Array with 3rd, 1st and 4th row:
[[ 7  8  9]
 [ 1  2  3]
 [10 11 12]]


### <font style="color:rgb(8,133,37)">1.3. Basic attributes of NumPy array</font>

Get a full list of attributes of an ndarray object [here](https://numpy.org/devdocs/user/quickstart.html).

In [42]:
print('Data type:\t{}'.format(np_array.dtype))
print('Array shape:\t{}'.format(np_array.shape))

Data type:	int64
Array shape:	(4, 3)


In [43]:
def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}\n'.format(array.shape))

array_info(np_array)

Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Data type:	int64
Array shape:	(4, 3)



### <font style="color:rgb(8,133,37)">1.4. Creating NumPy array using built-in functions and datatypes</font>

The full list of supported data types can be found [here](https://numpy.org/devdocs/user/basics.types.html).


**Sequence Array**

`np.arange([start, ]stop, [step, ]dtype=None)`

Return evenly spaced values in `[start, stop)`.

More delatis of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html).

In [44]:
# sequence array
array = np.arange(10, dtype=np.int64)
array_info(array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)



In [45]:
# sequence array
array = np.arange(5, 10, dtype=np.float64)
array_info(array)

Array:
[5. 6. 7. 8. 9.]
Data type:	float64
Array shape:	(5,)



**Zeroes Array**


In [46]:
# Zero array/matrix
zeros = np.zeros((2, 3), dtype=np.float32)
array_info(zeros)

Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Data type:	float32
Array shape:	(2, 3)



**Ones Array**


In [47]:
# ones array/matrix
ones = np.ones((3, 2), dtype=np.int8)
array_info(ones)

Array:
[[1 1]
 [1 1]
 [1 1]]
Data type:	int8
Array shape:	(3, 2)



**Constant Array**


In [48]:
# constant array/matrix
array = np.full((3, 3), 3.14)
array_info(array)

Array:
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
Data type:	float64
Array shape:	(3, 3)



**Identity Array**


In [49]:
# identity array/matrix
identity = np.eye(5, dtype=np.float32)      # identity matrix of shape 5x5
array_info(identity)

Array:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Data type:	float32
Array shape:	(5, 5)



**Random Integers Array**

`np.random.randint(low, high=None, size=None, dtype='l')`

Return random integer from the `discrete uniform` distribution in `[low, high)`. If high is `None`, then return elements are in `[0, low)`

More details can be found [here](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html).

In [50]:
# random integers array/matrix
rand_int = np.random.randint(5, 10, (2,3)) # random integer array of shape 2x3, values lies in [5, 10)
array_info(rand_int)

Array:
[[6 8 8]
 [5 9 6]]
Data type:	int64
Array shape:	(2, 3)



**Random Array**

`np.random.random(size=None)`

Results are from the `continuous uniform` distribution in `[0.0, 1.0)`.

These types of functions are useful is initializing the weight in Deep Learning. More details and similar functions can found [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.random.html).

In [51]:
# random array/matrix
random_array = np.random.random((5, 5))   # random array of shape 5x5
array_info(random_array)

Array:
[[0.7107646  0.36220719 0.56560888 0.31606556 0.74457929]
 [0.12566377 0.37652353 0.4220293  0.88088007 0.37444343]
 [0.85810053 0.57785423 0.98788856 0.7915028  0.37723164]
 [0.65581898 0.57325129 0.12434818 0.22854751 0.41182795]
 [0.80284543 0.79320759 0.66779371 0.64534275 0.05215703]]
Data type:	float64
Array shape:	(5, 5)



**Boolean Array**

If we compare above `random_array` with some `constant` or `array` of the same shape, we will get a boolean array.

In [52]:
# Boolean array/matrix
bool_array = random_array > 0.5
array_info(bool_array)

Array:
[[ True False  True False  True]
 [False False False  True False]
 [ True  True  True  True False]
 [ True  True False False False]
 [ True  True  True  True False]]
Data type:	bool
Array shape:	(5, 5)



### <font style="color:rgb(8,133,37)">1.5. Data type conversion</font>

Sometimes it is essential to convert one data type to another data type.

In [53]:
age_in_years = np.random.randint(0, 100, 10)
array_info(age_in_years)

Array:
[ 0 59 27 37 52 71 77 32 90  4]
Data type:	int64
Array shape:	(10,)



In [54]:
age_in_years = age_in_years.astype(np.uint8)
array_info(age_in_years)

Array:
[ 0 59 27 37 52 71 77 32 90  4]
Data type:	uint8
Array shape:	(10,)



In [55]:
age_in_years = age_in_years.astype(np.float128)
array_info(age_in_years)

Array:
[ 0. 59. 27. 37. 52. 71. 77. 32. 90.  4.]
Data type:	float128
Array shape:	(10,)



## <font color='blue'>2. Mathematical functions </font>

Numpy supports a lot of Mathematical operations with array/matrix. Here we will see a few of them which are useful in Deep Learning. All supported functions can be found [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html).

### <font style="color:rgb(8,133,37)">2.1. Exponential Function </font>
Exponential functions ( also called `exp` ) are used in neural networks as activations functions. They are used in softmax functions which is widely used in Classification tasks.

Return element-wise `exponential` of `array`.

More details of `np.exp` can be found **[here](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.exp.html#numpy.exp)**

In [56]:
array = np.array([np.full(3, -1), np.zeros(3), np.ones(3)])
array_info(array)

# exponential of a array/matrix
print('Exponential of an array:')
exp_array = np.exp(array)
array_info(exp_array)

Array:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
Data type:	float64
Array shape:	(3, 3)

Exponential of an array:
Array:
[[0.36787944 0.36787944 0.36787944]
 [1.         1.         1.        ]
 [2.71828183 2.71828183 2.71828183]]
Data type:	float64
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">2.2. Square Root </font>

`np.sqrt` return the element-wise `square-root` (`non-negative`) of an array.

More details of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html)

`Root Mean Square Error` (`RMSE`) and `Mean Absolute Error` (`MAE`) commonly used to measure the `accuracy` of continuous variables.

In [57]:
array = np.arange(10)
array_info(array)

print('Square root:')
root_array = np.sqrt(array)
array_info(root_array)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)

Square root:
Array:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
Data type:	float64
Array shape:	(10,)



### <font style="color:rgb(8,133,37)">2.3. Logrithm </font>

`np.log` return element-wise natural logrithm of an array.

More details of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html)

`Cross-Entropy` / `log loss` is the most commonly used loss in Machine Learning classification problem.

In [58]:
array = np.array([1, np.e, np.e**2, 1, 10])
array_info(array)

print('Logrithm:')
log_array = np.log(array)
array_info(log_array)

Array:
[ 1.          2.71828183  7.3890561   1.         10.        ]
Data type:	float64
Array shape:	(5,)

Logrithm:
Array:
[0.         1.         2.         0.         2.30258509]
Data type:	float64
Array shape:	(5,)



### <font style="color:rgb(8,133,37)">2.4. Power </font>

`numpy.power(x1, x2)`

Returns first array elements raised to powers from second array, element-wise.

Second array must be broadcastable to first array.

What is **broadcasting**? We will see later.

More detalis about the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html)

In [59]:
array = np.arange(0, 6, dtype=np.int64)
array_info(array)

print('Power 3:')
pow_array = np.power(array, 3)
array_info(pow_array)

Array:
[0 1 2 3 4 5]
Data type:	int64
Array shape:	(6,)

Power 3:
Array:
[  0   1   8  27  64 125]
Data type:	int64
Array shape:	(6,)



### <font style="color:rgb(8,133,37)">2.5. Clip Values </font>

`np.clip(a, a_min, a_max)`

Return element-wise cliped values between `a_min` and `a_max`.

More details of the finction can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html)

`Rectified Linear Unit` (`ReLU`) is the most commonly used activation function in Deep Learning.

What ReLU do?

If the value is less than zero, it makes it zero otherwise leave as it is. In NumPy assignment will be implementing this activation function using NumPy.

In [60]:
array = np.random.random((3, 3))
array_info(array)

# clipped between 0.2 and 0.5
print('Clipped between 0.2 and 0.5')
cliped_array = np.clip(array, 0.2, 0.5)
array_info(cliped_array)

# clipped to 0.2
print('Clipped to 0.2')
cliped_array = np.clip(array, 0.2, np.inf)
array_info(cliped_array)

Array:
[[0.6348076  0.61306632 0.20749883]
 [0.49494183 0.13287421 0.50310419]
 [0.56882461 0.11163352 0.62738899]]
Data type:	float64
Array shape:	(3, 3)

Clipped between 0.2 and 0.5
Array:
[[0.5        0.5        0.20749883]
 [0.49494183 0.2        0.5       ]
 [0.5        0.2        0.5       ]]
Data type:	float64
Array shape:	(3, 3)

Clipped to 0.2
Array:
[[0.6348076  0.61306632 0.20749883]
 [0.49494183 0.2        0.50310419]
 [0.56882461 0.2        0.62738899]]
Data type:	float64
Array shape:	(3, 3)



## <font color='blue'>3. Reshape ndarray </font>

Reshaping the array / matrix is very often required in Machine Learning and Computer vision.

### <font style="color:rgb(8,133,37)">3.1. Reshape </font>

`np.reshape` gives an array in new shape, without changing its data.

More details of the function can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)


In [64]:
a = np.arange(1, 10, dtype=np.int64)
array_info(a)

print('Reshape to 3x3:')
a_3x3 = a.reshape(3, 3)
array_info(a_3x3)

print('Reshape 3x3 to 3x3x1:')
a_3x3x1 = a_3x3.reshape(3, 3, 1)
array_info(a_3x3x1)

Array:
[1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(9,)

Reshape to 3x3:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)

Reshape 3x3 to 3x3x1:
Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Data type:	int64
Array shape:	(3, 3, 1)



### <font style="color:rgb(8,133,37)">3.2. Expand Dim </font>

`np.expand_dims`

In the last reshape, we have added a new axis. We can use `np.expand_dims` or `np.newaxis` to do the same thing.

Mode details for `np.expand_dim` can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html)

In [62]:
print('Using np.expand_dims:')
a_expand = np.expand_dims(a_3x3, axis=2)
array_info(a_expand)

print('Using np.newaxis:')
a_newaxis = a_3x3[..., np.newaxis]
# or
# a_newaxis = a_3x3[:, :, np.newaxis]
array_info(a_newaxis)

Using np.expand_dims:
Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Data type:	int64
Array shape:	(3, 3, 1)

Using np.newaxis:
Array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Data type:	int64
Array shape:	(3, 3, 1)



### <font style="color:rgb(8,133,37)">3.3. Squeeze </font>

Sometimes we need to remove the redundant axis (single-dimensional entries). We can use `np.squeeze` to do this.

More details of `np.squeeze` can be found [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html)

Deep Learning very often uses this functionality.

In [94]:
a_newaxis.shape

(3, 3, 1)

In [95]:
print('Squeeze along axis=2:')
a_squeezed = np.squeeze(a_newaxis, axis=2)
array_info(a_squeezed)

# should get value error
# print('Squeeze along axis=1, should get ValueError')
# a_squeezed_error = np.squeeze(a_newaxis, axis=1)  # Getting error because of the size of
                                                  # axis-1 is not equal to one.

Squeeze along axis=2:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">3.4. Reshape revisit </font>

We have a 1-d array of length n. We want to reshape in a 2-d array such that the number of columns becomes two, and we do not care about the number of rows.

In [65]:
a = np.arange(10)
array_info(a)

print('Reshape such that number of column is 2:')
a_col_2 = a.reshape(-1, 2)
array_info(a_col_2)

Array:
[0 1 2 3 4 5 6 7 8 9]
Data type:	int64
Array shape:	(10,)

Reshape such that number of column is 2:
Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Data type:	int64
Array shape:	(5, 2)



## <font color='blue'>4. Combine Arrays / Matrix </font>

Combining two or more arrays is a frequent operation in machine learning. Let's have a look at a few methods.


### <font style="color:rgb(8,133,37)">4.1. Concatenate </font>

`np.concatenate`, Join a sequence of arrays along an existing axis.

More details of the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html)

In [66]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9]])

print('Concatenate along axis zero:')
array = np.concatenate((a1, a2), axis=0)
array_info(array)

Concatenate along axis zero:
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">4.2. hstack </font>

`np.hstack`, stack arrays in sequence horizontally (column-wise).

More details of the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack)

In [67]:
a1 = np.array((1, 2, 3))
a2 = np.array((4, 5, 6))
a_hstacked = np.hstack((a1,a2))

print('Horizontal stack:')
array_info(a_hstacked)

Horizontal stack:
Array:
[1 2 3 4 5 6]
Data type:	int64
Array shape:	(6,)



In [68]:
a1 = np.array([[1],[2],[3]])
a2 = np.array([[4],[5],[6]])
a_hstacked = np.hstack((a1,a2))

print('Horizontal stack:')
array_info(a_hstacked)

Horizontal stack:
Array:
[[1 4]
 [2 5]
 [3 6]]
Data type:	int64
Array shape:	(3, 2)



### <font style="color:rgb(8,133,37)">4.3. vstack </font>

`np.vstack`, tack arrays in sequence vertically (row-wise).

More details of the function find [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html#numpy.vstack)

In [69]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a_vstacked = np.vstack((a1, a2))

print('Vertical stack:')
array_info(a_vstacked)

Vertical stack:
Array:
[[1 2 3]
 [4 5 6]]
Data type:	int64
Array shape:	(2, 3)



In [70]:
a1 = np.array([[1, 11], [2, 22], [3, 33]])
a2 = np.array([[4, 44], [5, 55], [6, 66]])
a_vstacked = np.vstack((a1, a2))

print('Vertical stack:')
array_info(a_vstacked)

Vertical stack:
Array:
[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]
Data type:	int64
Array shape:	(6, 2)



## <font color='blue'>5. Element wise Operations </font>


In [71]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.17694138 0.69589421 0.92968613 0.09941835]
 [0.41896759 0.00930806 0.15170833 0.93628477]
 [0.83533443 0.85924203 0.39773266 0.2800945 ]
 [0.70820533 0.99253318 0.20604955 0.08085826]]
Data type:	float64
Array shape:	(4, 4)

Array:
[[0.61851056 0.13122548 0.35730668 0.89341592]
 [0.81477992 0.42452628 0.60779279 0.66093544]
 [0.45592834 0.57908603 0.18452506 0.91982847]
 [0.70118699 0.36590505 0.4950989  0.5986261 ]]
Data type:	float64
Array shape:	(4, 4)



### <font style="color:rgb(8,133,37)">5.1. Element wise Scalar Operation </font>

In [72]:
a + 5 # element wise scalar addition

array([[5.17694138, 5.69589421, 5.92968613, 5.09941835],
       [5.41896759, 5.00930806, 5.15170833, 5.93628477],
       [5.83533443, 5.85924203, 5.39773266, 5.2800945 ],
       [5.70820533, 5.99253318, 5.20604955, 5.08085826]])

In [73]:
a - 5 # element wise scalar subtraction

array([[-4.82305862, -4.30410579, -4.07031387, -4.90058165],
       [-4.58103241, -4.99069194, -4.84829167, -4.06371523],
       [-4.16466557, -4.14075797, -4.60226734, -4.7199055 ],
       [-4.29179467, -4.00746682, -4.79395045, -4.91914174]])

In [74]:
a * 10 # element wise scalar multiplication

array([[1.76941384, 6.95894208, 9.29686133, 0.99418348],
       [4.18967589, 0.09308061, 1.5170833 , 9.36284769],
       [8.35334428, 8.59242032, 3.9773266 , 2.80094499],
       [7.0820533 , 9.9253318 , 2.06049546, 0.8085826 ]])

In [75]:
a/10 # element wise scalar division

array([[0.01769414, 0.06958942, 0.09296861, 0.00994183],
       [0.04189676, 0.00093081, 0.01517083, 0.09362848],
       [0.08353344, 0.0859242 , 0.03977327, 0.02800945],
       [0.07082053, 0.09925332, 0.02060495, 0.00808583]])

### <font style="color:rgb(8,133,37)">5.2. Element wise Array Operations </font>


In [76]:
a + b # element wise array/vector addition

array([[0.79545194, 0.82711968, 1.28699281, 0.99283427],
       [1.23374751, 0.43383434, 0.75950112, 1.59722021],
       [1.29126277, 1.43832807, 0.58225772, 1.19992297],
       [1.40939232, 1.35843823, 0.70114845, 0.67948436]])

In [77]:
a - b # element wise array/vector subtraction

array([[-0.44156917,  0.56466873,  0.57237945, -0.79399757],
       [-0.39581233, -0.41521822, -0.45608445,  0.27534933],
       [ 0.37940609,  0.280156  ,  0.2132076 , -0.63973397],
       [ 0.00701834,  0.62662813, -0.28904936, -0.51776784]])

In [78]:
a * b # element wise array/vector multiplication

array([[0.10944011, 0.09131905, 0.33218306, 0.08882194],
       [0.34136638, 0.00395152, 0.09220723, 0.61882378],
       [0.38085264, 0.49757506, 0.07339164, 0.25763889],
       [0.49658436, 0.3631729 , 0.1020149 , 0.04840387]])

In [79]:
a / b # element wise array/vector division

array([[0.28607658, 5.30304202, 2.60192766, 0.11127891],
       [0.51420951, 0.02192576, 0.24960535, 1.41660549],
       [1.83216167, 1.48378994, 2.15543977, 0.30450732],
       [1.01000923, 2.71254299, 0.41617855, 0.13507306]])

In [80]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 2)
array_info(c)
# Should throw ValueError
a + c

Array "a":
Array:
[[0.17694138 0.69589421 0.92968613 0.09941835]
 [0.41896759 0.00930806 0.15170833 0.93628477]
 [0.83533443 0.85924203 0.39773266 0.2800945 ]
 [0.70820533 0.99253318 0.20604955 0.08085826]]
Data type:	float64
Array shape:	(4, 4)

Array "c":
Array:
[[0.67908715 0.65814975]
 [0.07906119 0.41856966]]
Data type:	float64
Array shape:	(2, 2)



ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

### <font style="color:rgb(8,133,37)">5.3. Broadcasting </font>

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array.

Let's try to understand with a simple example.

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a+b)  # b is reshaped such that it can be added to a.


# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)

Array "b":
Array:
[0 1 0]
Data type:	int64
Array shape:	(3,)

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int64
Array shape:	(3, 3)



## <font color='blue'>6. Linear Algebra</font>

Here we see commonly use linear algebra operations in Machine Learning.

### <font style="color:rgb(8,133,37)">6.1. Transpose </font>


In [82]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()
array_info(a_transpose)

Array "a":
Array:
[[0.87310871 0.96593741 0.83405913]
 [0.75698328 0.70053423 0.76384432]]
Data type:	float64
Array shape:	(2, 3)

Transose of "a":
Array:
[[0.87310871 0.75698328]
 [0.96593741 0.70053423]
 [0.83405913 0.76384432]]
Data type:	float64
Array shape:	(3, 2)



### <font style="color:rgb(8,133,37)">6.2. Matrix Multiplication</font>
We will discuss 2 ways of performing Matrix Multiplication.

- `matmul`
- Python `@` operator

**Using matmul function in numpy**
This is the most used approach for multiplying two matrices using Numpy. [See docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html)

In [83]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

c = np.matmul(a,b) # matrix multiplication of a and b

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim1 of a and dim0 of b has to be
                                                        # same for matrix multiplication

Array "a":
Array:
[[0.25598463 0.11268454 0.91047894 0.19156728]
 [0.91928768 0.6600787  0.14807884 0.20857455]
 [0.70812449 0.07545561 0.29716475 0.76406772]]
Data type:	float64
Array shape:	(3, 4)

Array "b"
Array:
[[0.0195098  0.68115098]
 [0.92865672 0.21312278]
 [0.86334053 0.27734624]
 [0.35088681 0.03721006]]
Data type:	float64
Array shape:	(4, 2)

matrix multiplication of a and b:
Array:
[[0.96291126 0.45802597]
 [0.83195016 0.81568169]
 [0.60854338 0.60926953]]
Data type:	float64
Array shape:	(3, 2)

(3, 4) x (4, 2) --> (3, 2)


In [84]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

c = a@b # matrix multiplication of a and b
array_info(c)

Array "a":
Array:
[[0.19234996 0.55252969 0.85783199 0.35518183]
 [0.75228047 0.20215772 0.4575088  0.69009038]
 [0.03864801 0.5544751  0.1581461  0.0489392 ]]
Data type:	float64
Array shape:	(3, 4)

Array "b"
Array:
[[0.47204625 0.78318867]
 [0.83752561 0.39204343]
 [0.55528676 0.8136361 ]
 [0.60343968 0.9240015 ]]
Data type:	float64
Array shape:	(4, 2)

Array:
[[1.2442294  1.39341356]
 [1.19489994 1.67832236]
 [0.59997903 0.42154027]]
Data type:	float64
Array shape:	(3, 2)



### <font style="color:rgb(8,133,37)">6.3. Inverse</font>

In [85]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)
A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.1344096  0.95999728 0.46024698]
 [0.48101928 0.57255329 0.05514657]
 [0.64348459 0.56892342 0.17287408]]
Data type:	float64
Array shape:	(3, 3)

Inverse of "A" ("A_inverse"):
Array:
[[-0.8419963  -1.19422623  2.62262415]
 [ 0.59370651  3.39917286 -2.66497065]
 [ 1.18027012 -6.74133975  4.79277178]]
Data type:	float64
Array shape:	(3, 3)

"A x A_inverse = Identity" should be true:
Array:
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.32667268e-17 1.00000000e+00 1.66533454e-16]
 [5.55111512e-17 0.00000000e+00 1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)



### <font style="color:rgb(8,133,37)">6.4. Dot Product</font>


In [86]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

dot_pro = np.dot(a, b)  # It will be a scalar, so its shape will be empty
array_info(dot_pro)

Array:
70
Data type:	int64
Array shape:	()



## <font color='blue'>7. Array statistics</font>


### <font style="color:rgb(8,133,37)">7.1. Sum</font>


In [87]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### <font style="color:rgb(8,133,37)">7.2. Sum along Axis</font>


In [88]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('')

print('sum along 0th axis = ',a.sum(axis = 0)) # sum along 0th axis ie: 1+4, 2+5, 3+6
print("")
print('sum along 1st axis = ',a.sum(axis = 1)) # sum along 1st axis ie: 1+2+3, 4+5+6

[[1 2 3]
 [4 5 6]]

sum along 0th axis =  [5 7 9]

sum along 1st axis =  [ 6 15]


### <font style="color:rgb(8,133,37)">7.3. Minimum and Maximum</font>


In [89]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### <font style="color:rgb(8,133,37)">7.4. Min and Max along Axis</font>


In [90]:
a = np.array([[-2, 0, 2], [1, 2, 3]])

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

a =
 [[-2  0  2]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  3

Minimum along axis 0 =  [-2  0  2]
Maximum along axis 0 =  [1 2 3]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [2 3]


### <font style="color:rgb(8,133,37)">7.5. Mean and Standard Deviation</font>


In [91]:
a = np.array([-1, 0, -0.4, 1.2, 1.43, -1.9, 0.66])

print('mean of the array = ',a.mean())
print('standard deviation of the array = ',a.std())

mean of the array =  -0.001428571428571414
standard deviation of the array =  1.1142252730860458


### <font style="color:rgb(8,133,37)">7.6. Standardizing the Array</font>

Make distribution of array elements such that`mean=0` and `std=1`.

In [92]:
a = np.array([-1, 0, -0.4, 1.2, 1.43, -1.9, 0.66])

print('mean of the array = ',a.mean())
print('standard deviation of the array = ',a.std())
print()

standardized_a = (a - a.mean())/a.std()
print('Standardized Array = ', standardized_a)
print()

print('mean of the standardized array = ',standardized_a.mean()) # close to 0
print('standard deviation of the standardized  array = ',standardized_a.std()) # equals to 1

mean of the array =  -0.001428571428571414
standard deviation of the array =  1.1142252730860458

Standardized Array =  [-8.96202458e-01  1.28212083e-03 -3.57711711e-01  1.07826362e+00
  1.28468507e+00 -1.70393858e+00  5.93621943e-01]

mean of the standardized array =  -3.172065784643304e-17
standard deviation of the standardized  array =  1.0


# <font color='blue'>References </font>

https://numpy.org/devdocs/user/quickstart.html

https://numpy.org/devdocs/user/basics.types.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

https://coolsymbol.com/emojis/emoji-for-copy-and-paste.html

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.exp.html#numpy.exp

https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack

https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html#numpy.vstack